In [2]:
import numpy as np

Forked from mrdbourke's repo https://github.com/mrdbourke/zero-to-mastery-ml/blob/master/section-2-data-science-and-ml-tools/introduction-to-numpy.ipynb

## 1. Creating an array
 - np.array
 - np.ones
 - np.zeros
 - np.unique
 - np.random.rand
 - np.random.randint

In [3]:
simple_array = np.array([1, 2, 3])
simple_array

array([1, 2, 3])

In [5]:
ones = np.ones((10, 2))

In [6]:
print(ones.dtype)

float64


In [7]:
ones.astype(int)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [8]:
np.zeros((5, 3, 3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [9]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [11]:
np.random.randint(10, size=(5, 3))

array([[9, 5, 8],
       [7, 7, 0],
       [2, 9, 9],
       [3, 4, 6],
       [1, 4, 0]])

In [12]:
np.random.random((5, 3))

array([[0.70373752, 0.42984188, 0.04754254],
       [0.98558226, 0.03655862, 0.10287571],
       [0.07621545, 0.43508925, 0.1505678 ],
       [0.30079698, 0.72213319, 0.17251895],
       [0.78448656, 0.21212872, 0.45489496]])

In [13]:
np.random.rand(5, 3)

array([[0.84822272, 0.37990198, 0.78514235],
       [0.40625451, 0.37565369, 0.41559202],
       [0.65652018, 0.05278957, 0.05826183],
       [0.46905835, 0.36259945, 0.40729147],
       [0.53789783, 0.89306633, 0.22844568]])

## 2. Viewing arrays & matrices (Indexing)

In [14]:
oned = np.array([1, 2, 3])
twod = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])
threed = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]]])

print(oned)
print(twod)
print(threed)

[1 2 3]
[[1.  2.  3.3]
 [4.  5.  6.5]]
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [15]:
print(oned[0], twod[0], threed[0])

1 [1.  2.  3.3] [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
twod[1]

array([4. , 5. , 6.5])

In [17]:
threed[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [20]:
fourd = np.random.randint(10, size=(2, 3, 4, 5))
fourd.shape

(2, 3, 4, 5)

In [21]:
fourd[:, :, :, :4]

array([[[[2, 2, 8, 6],
         [3, 4, 5, 3],
         [5, 0, 3, 2],
         [6, 1, 3, 3]],

        [[1, 5, 9, 3],
         [2, 0, 4, 1],
         [3, 7, 1, 6],
         [2, 3, 4, 9]],

        [[7, 2, 1, 7],
         [2, 3, 9, 4],
         [5, 3, 5, 0],
         [7, 1, 3, 0]]],


       [[[0, 1, 9, 1],
         [6, 5, 6, 2],
         [0, 4, 7, 5],
         [8, 0, 0, 1]],

        [[7, 3, 8, 4],
         [4, 7, 7, 2],
         [7, 8, 9, 9],
         [3, 4, 2, 9]],

        [[0, 4, 1, 6],
         [2, 0, 4, 0],
         [7, 1, 3, 1],
         [0, 4, 6, 4]]]])

In [61]:
oned

array([1, 2, 3])

In [62]:
oned[oned > 2]

array([3])

In [63]:
oned[oned >= 2]

array([2, 3])

## 3. Manipulating & Comparing arrays
 - 3.1 Arithematic
     - +, -, *, /, //, **, %
     - np.exp, np.log
     - np.dot
 - 3.2 Aggregation
     - np.sum, np.sum(x>3),
     - np.mean, np.std,
     - np.var, np.min, np.max
     - np.argmin, np.argmax
     - np.reshape, mat.T
 - 3.3 Comparision
     - `>` , >=, <, <=, !=, ==

In [22]:
oned

array([1, 2, 3])

In [23]:
ones = np.ones(3)

In [24]:
oned + ones

array([2., 3., 4.])

In [25]:
oned - ones

array([0., 1., 2.])

In [26]:
oned * ones

array([1., 2., 3.])

In [28]:
oned * twod

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [29]:
twod * threed # doesnt work

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [31]:
np.random.random((5, 3)) @ np.random.random((3, 4))

array([[0.82615269, 0.4814075 , 0.33376826, 0.73606493],
       [0.91102043, 0.36932286, 0.6270089 , 0.89667066],
       [1.54888702, 1.05618895, 0.88359061, 1.16715627],
       [0.81580341, 0.46323103, 0.41429104, 0.71615424],
       [1.19045951, 0.76285394, 0.94558103, 0.87357086]])

In [32]:
np.log(twod)

array([[0.        , 0.69314718, 1.19392247],
       [1.38629436, 1.60943791, 1.87180218]])

In [33]:
np.exp(twod)

array([[  2.71828183,   7.3890561 ,  27.11263892],
       [ 54.59815003, 148.4131591 , 665.14163304]])

In [34]:
threed % 2

array([[[1, 0, 1],
        [0, 1, 0],
        [1, 0, 1]],

       [[0, 1, 0],
        [1, 0, 1],
        [0, 1, 0]]])

In [35]:
np.sum(threed)

171

In [36]:
np.min(fourd)

0

In [37]:
np.max(fourd)

9

In [38]:
np.std(twod)

1.8226964152656422

In [39]:
np.var(twod)

3.3222222222222224

In [40]:
np.sqrt(np.var(twod))

1.8226964152656422

In [41]:
twod

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [42]:
twod.shape

(2, 3)

In [43]:
twod.reshape(2, 3, 1)

array([[[1. ],
        [2. ],
        [3.3]],

       [[4. ],
        [5. ],
        [6.5]]])

In [44]:
twod.reshape(2, 3, 1) + threed

array([[[ 2. ,  3. ,  4. ],
        [ 6. ,  7. ,  8. ],
        [10.3, 11.3, 12.3]],

       [[14. , 15. , 16. ],
        [18. , 19. , 20. ],
        [22.5, 23.5, 24.5]]])

In [45]:
twod

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [46]:
twod.T

array([[1. , 4. ],
       [2. , 5. ],
       [3.3, 6.5]])

In [47]:
matrix = np.random.random(size=(5, 3, 3))
matrix

array([[[0.52958874, 0.41543137, 0.59691212],
        [0.99741286, 0.11798962, 0.70701019],
        [0.36327922, 0.08395481, 0.13604313]],

       [[0.19801631, 0.27906454, 0.87152223],
        [0.37918633, 0.93810441, 0.56797949],
        [0.61012578, 0.41992831, 0.87704688]],

       [[0.07621179, 0.85571743, 0.09375643],
        [0.79829755, 0.68873796, 0.27184448],
        [0.93954841, 0.02026145, 0.95514103]],

       [[0.86505865, 0.57025643, 0.46309999],
        [0.94278095, 0.56047033, 0.82182622],
        [0.95953661, 0.16310744, 0.63169613]],

       [[0.8397489 , 0.08794668, 0.8219431 ],
        [0.30726411, 0.29469308, 0.72786074],
        [0.13565636, 0.13920034, 0.39135728]]])

In [48]:
matrix.T

array([[[0.52958874, 0.19801631, 0.07621179, 0.86505865, 0.8397489 ],
        [0.99741286, 0.37918633, 0.79829755, 0.94278095, 0.30726411],
        [0.36327922, 0.61012578, 0.93954841, 0.95953661, 0.13565636]],

       [[0.41543137, 0.27906454, 0.85571743, 0.57025643, 0.08794668],
        [0.11798962, 0.93810441, 0.68873796, 0.56047033, 0.29469308],
        [0.08395481, 0.41992831, 0.02026145, 0.16310744, 0.13920034]],

       [[0.59691212, 0.87152223, 0.09375643, 0.46309999, 0.8219431 ],
        [0.70701019, 0.56797949, 0.27184448, 0.82182622, 0.72786074],
        [0.13604313, 0.87704688, 0.95514103, 0.63169613, 0.39135728]]])

In [49]:
matrix.shape, matrix.T.shape

((5, 3, 3), (3, 3, 5))

In [52]:
np.dot(np.random.randint(15, size=(5,3)), np.random.randint(12, size=(3, 4)))

array([[ 51, 151, 147,  73],
       [ 65, 248, 212, 130],
       [ 17,  67,  59,  27],
       [ 55, 124, 136,  70],
       [ 64, 237, 205, 125]])

In [54]:
np.random.randint(15, size=(5,3)) * np.random.randint(9, size=(3, 3))

ValueError: operands could not be broadcast together with shapes (5,3) (3,3) 

In [55]:
np.random.randint(9, size=(3,3)) * np.random.randint(9, size=(3, 3))

array([[ 6, 15, 15],
       [ 0, 36,  0],
       [32,  0, 14]])

In [56]:
oned > twod

array([[False, False, False],
       [False, False, False]])

In [57]:
oned > 5

array([False, False, False])

In [58]:
oned == oned

array([ True,  True,  True])

## 4. Sorting Arrays
 - np.sort, np.argsort
 - np.argmax, np.argmin

In [69]:
random_array = np.random.random((2,3))

In [70]:
random_array

array([[0.90694113, 0.84394815, 0.20318086],
       [0.12416733, 0.11164593, 0.22410209]])

In [71]:
np.sort(random_array)

array([[0.20318086, 0.84394815, 0.90694113],
       [0.11164593, 0.12416733, 0.22410209]])

In [72]:
np.argsort(random_array)

array([[2, 1, 0],
       [1, 0, 2]])

In [73]:
np.argmin(random_array)

4

In [75]:
np.argmin(random_array, axis=0)

array([1, 1, 0])

In [80]:
np.argmin(random_array, axis=1)

array([2, 1])

In [76]:
np.argmax(random_array)

0

In [78]:
np.argmax(random_array, axis=1)

array([0, 2])

In [81]:
np.argmax(random_array, axis=0)

array([0, 0, 1])

axis = 0 -> Column


axis = 1 -> Row 